[toolchain]
package_manager = "yarn"

[features]
seeds = false
skip-lint = false

[programs.localnet]
rps_game = "FD79uPpUdF6KQTiqd2V387UkP29uJtHFJvH2J66uemsL"

[programs.devnet]
rps_game = "FD79uPpUdF6KQTiqd2V387UkP29uJtHFJvH2J66uemsL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

# MagicBlock endpoints for development
# Solana Devnet: https://api.devnet.solana.com
# MagicBlock Devnet: https://devnet.magicblock.app
# Magic Router Devnet: https://devnet-rpc.magicblock.app

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
